apiVersion: v1
kind: Service
metadata:
  name: svc-calc
  labels:
    app.kubernetes.io/name: svc-calc
    app.kubernetes.io/part-of: vmetrix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: svc-calc
  ports:
    - name: http
      port: 80
      targetPort: http
