apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-calc
spec:
  replicas: 2
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: svc-calc
      containers:
        - name: svc-calc
          env:
            - name: INFO_APP_ENVIRONMENT
              value: production
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              memory: 768Mi
