server:
  port: 8081

spring:
  application:
    name: svc-misc

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: "@project.version@"
    description: "VMETRIX Misc Utilities Microservice"
